on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      # Relative path from the root of your repo to the build.yaml
      build_matrix_path: "zmk-software/build.yaml"
      # Relative path from the root of your repo to the config folder
      config_path: "zmk-software/config"
