on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      # Path to the build.yaml relative to the repository root
      build_matrix_path: "zmk-software/build.yaml"
      # Path to your config folder relative to the repository root
      config_path: "zmk-software/config"
